### ISSUE TITLE
400 (BAD REQUEST)

### ISSUE THREAD

**Issue by zhenwu-cn** [mohamed-aziz/todoapp#1]
I created a newtodo on one page, another page could not get the notify：
`  $.notify("Someone added a todo.", "info");`
and browser got error:
`http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=LgZEwle&sid=fcb61d937bd64d7bbd3fb1338a834279 400 (BAD REQUEST)`

here is my start command:
`gunicorn --worker-class=gevent -w 4 manage:app --bind=0.0.0.0:5000 --log-level=DEBUG`

**Comment by realazizk** [comment]
This is an issue with gunicorn, you can run gunicorn with only one worker, it seems that gunicorn doesn't support sticky sessions yet.

Take a look here: https://flask-socketio.readthedocs.io/en/latest/#gunicorn-web-server

miguelgrinberg/Flask-SocketIO#402
